### ISSUE TITLE
generate php code on mac does not seem to work

### ISSUE THREAD

**Issue by stijnblommerde** [pedro151/starumlPHP#9]
staruml 2.5.0
mac osx 10.9.5

bug: 
create class diagrams > generate php code from model > empty model folder

**Comment by dehart** [comment]
I got the same issue here on v2.5.1 + Ubuntu 15.10

**Comment by Chiplex** [comment]
staruml 2.5.0
win10 

bug:
create class diagrams > generate php code from model > empty model folder

**Comment by pedro151** [comment]
RE: Tool >> PHP >> Generate code >> [ select your model ] >> select your paste
1. Click the menu (Tools > PHP > Generate Code...)
2. Select a base model (or package) that will be generated to PHP.
3. Select a folder where generated PHP source files will be placed.

**Comment by dehart** [comment]
It works when PHP strict mode is turned off in Tools >> PHP >> Configure...
Also turned Node debugger on for testing. Debug >> Enable Node Debugger
Otherwise it generates an empty folder

Debug console log sometimes shows:
Uncaught TypeError: Cannot read property 'type' of null PHPCodeGenerator.js:284

**Comment by pedro151** [comment]
I checked, when generates UML without type with strict mode an error occurs.
will be fixed in 1.2
